#
# Available touch parts of Maggie robot:
#

int32 NUMBER_SENSORS    = 11

string HEAD             = "head"
string LEFT_BACK        = "left_back"
string LEFT_SIDE        = "left_side"
string LEFT_SHOULDER    = "left_shoulder"
string LEFT_FOREARM     = "left_forearm"
string LEFT_HAND        = "left_hand"
string RIGHT_BACK       = "right_back"
string RIGHT_SIDE       = "right_side"
string RIGHT_SHOULDER   = "right_shoulder"
string RIGHT_FOREARM    = "right_forearm"
string RIGHT_HAND       = "right_hand"
